name: structdiff
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - tqdm
  - pyyaml
  - pip
  - pip:
    - transformers>=4.30.0
    - omegaconf
    - wandb
    - biopython
    - fair-esm
    - pytest
    - pytest-cov
    - black
    - flake8
    - isort
    - scipy
    - h5py
    - tensorboard