# Classification configuration for antimicrobial peptide classification
experiment:
  name: "amp_classification"
  output_dir: "outputs"
  seed: 42

# Task configuration
task:
  type: "classification"  # 区别于生成任务
  num_classes: 3  # 0=抗菌肽, 1=抗真菌肽, 2=抗病毒肽
  use_weights: true  # 使用样本权重
  class_names: ["抗菌肽", "抗真菌肽", "抗病毒肽"]

# Model configuration
model:
  # Sequence encoder settings
  sequence_encoder:
    pretrained_model: "facebook/esm2_t6_8M_UR50D"
    freeze_encoder: false
    hidden_dim: 320
    
  # Classification head
  classifier:
    hidden_dim: 320
    dropout: 0.1
    num_layers: 2  # 分类头的层数
    
  # Structure encoder settings (可选)
  structure_encoder:
    type: "MultiScaleStructureEncoder"
    use_esmfold: false  # 分类任务可以不使用ESMFold
    hidden_dim: 320
    
  # Loss weights
  loss_weights:
    classification_loss: 1.0
    regularization_loss: 0.1

# Data configuration
data:
  train_path: "data/processed/train.csv"
  val_path: "data/processed/val.csv"
  test_path: "data/processed/test.csv"
  batch_size: 16  # 分类任务可以用更大的batch size
  num_workers: 4
  pin_memory: true
  max_length: 100  # 根据数据统计调整
  min_length: 5
  use_predicted_structures: false  # 分类任务暂不使用结构
  
  # Data augmentation for classification
  augmentation:
    enable: true
    mask_prob: 0.1  # 轻微的随机mask
    noise_prob: 0.05  # 添加轻微噪声

# Training configuration
training:
  num_epochs: 50  # 分类任务通常需要更多epochs
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0
  use_amp: false
  use_ema: false
  validate_every: 2  # 每2个epoch验证一次
  early_stopping:
    patience: 10
    min_delta: 0.001
  
  # Optimizer settings
  optimizer:
    name: "adamw"
    lr: 2e-5  # 分类任务通常用较小的学习率
    weight_decay: 0.01
    betas: [0.9, 0.999]
    
  # Scheduler settings
  scheduler:
    name: "cosine"
    min_lr: 1e-6
    warmup_epochs: 5

# Evaluation metrics
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "auc_roc"
    - "confusion_matrix"
  
  # Class-wise metrics
  per_class_metrics: true

# Logging configuration
logging:
  log_level: "INFO"
  log_every: 10
  save_predictions: true  # 保存预测结果

# Weights & Biases configuration
wandb:
  enabled: false
  project: "amp-classification"
  tags: ["classification", "antimicrobial"] 