# ESMFold CPU配置
experiment:
  name: "peptide_esmfold_cpu_evaluation"
  
model:
  structure_encoder:
    esmfold_config:
      device: "cpu"  # 强制使用CPU
      use_fp16: false  # CPU不支持FP16
      chunk_size: 64   # 减小chunk大小
      max_sequence_length: 200  # 限制最大序列长度
      
# 评估配置 - CPU优化
evaluation:
  esmfold_cpu_mode: true
  max_eval_sequences: 50  # 限制评估序列数量
  eval_batch_size: 2      # 小批次
  
# 内存优化
memory_optimization:
  esmfold_cpu_fallback: true
  aggressive_cleanup: true
  chunk_evaluation: true