# StructDiff分离式训练优化配置
# 解决内存和多进程问题
experiment:
  name: "structdiff_separated_optimized_v1"
  description: "修复内存和多进程问题的优化训练"
  project: "StructDiff-Production"
  seed: 42

# 模型配置 - 减少内存使用
model:
  type: "StructDiff"
  
  sequence_encoder:
    pretrained_model: "facebook/esm2_t6_8M_UR50D"
    freeze_encoder: false
    use_lora: false
    
  structure_encoder:
    type: "multi_scale"
    hidden_dim: 320        # 匹配去噪器维度
    use_esmfold: true
    use_cache: true
    cache_dir: "./cache"
    
    local:
      hidden_dim: 320      # 匹配去噪器维度
      num_layers: 2        # 减少层数
      kernel_sizes: [3, 5]
      dropout: 0.1
      
    global:
      hidden_dim: 320      # 匹配去噪器维度
      num_attention_heads: 8  # 320能被8整除
      num_layers: 2        # 减少层数
      dropout: 0.1
      
    fusion:
      method: "attention"
      hidden_dim: 320      # 匹配去噪器维度
  
  denoiser:
    hidden_dim: 320
    num_layers: 6          # 减少层数
    num_heads: 8           # 320能被8整除
    dropout: 0.1
    use_cross_attention: true
    
  sequence_decoder:
    hidden_dim: 320
    num_layers: 3          # 减少层数
    vocab_size: 33
    dropout: 0.1

# 扩散过程配置
diffusion:
  num_timesteps: 1000
  noise_schedule: "sqrt"
  beta_start: 0.0001
  beta_end: 0.02
  sampling_method: "ddpm"
  ddim_steps: 50

# 分离式训练配置 - 优化内存使用
separated_training:
  stage1:
    epochs: 20             # 减少epochs用于测试
    batch_size: 1          # 最小批次避免内存问题
    learning_rate: 1e-4
    warmup_steps: 100      # 减少warmup步数
    gradient_clip: 1.0
    
    optimizer:
      type: "AdamW"
      weight_decay: 0.01
      betas: [0.9, 0.999]
      eps: 1e-8
    
    scheduler:
      type: "cosine"
      eta_min: 1e-6
  
  stage2:
    epochs: 10
    batch_size: 2
    learning_rate: 5e-5
    warmup_steps: 50
    gradient_clip: 0.5
    
    optimizer:
      type: "AdamW"
      weight_decay: 0.01
      betas: [0.9, 0.999]
      eps: 1e-8
    
    scheduler:
      type: "cosine"
      eta_min: 1e-6

# 数据配置 - 禁用多进程
data:
  data_dir: "./data/processed"
  train_file: "train.csv"
  val_file: "val.csv"
  test_file: "test.csv"
  
  max_length: 50
  min_length: 5
  
  # 数据加载 - 完全禁用多进程
  num_workers: 0         # 禁用多进程
  pin_memory: false      # 禁用pin_memory减少内存使用
  prefetch_factor: 2
  
  # 结构特征配置
  use_predicted_structures: true
  structure_cache_dir: "./cache"

# 长度控制配置
length_control:
  enabled: true
  min_length: 5
  max_length: 50
  analyze_training_data: true
  save_distributions: true
  length_penalty_weight: 0.1
  
  type_specific_lengths:
    antimicrobial: [20, 8]
    antifungal: [25, 10]
    antiviral: [30, 12]
    general: [25, 5]

# 分类器自由引导配置
classifier_free_guidance:
  enabled: true
  dropout_prob: 0.1
  guidance_scale: 2.0
  adaptive_guidance: true
  guidance_schedule: "cosine"

# 训练增强配置 - 减少内存使用
training_enhancements:
  use_amp: false         # 暂时禁用AMP避免复杂性
  amp_dtype: "float16"
  
  use_ema: false         # 禁用EMA减少内存
  ema_decay: 0.9999
  ema_update_every: 10
  
  gradient_accumulation_steps: 4  # 增加梯度累积补偿小批次
  
  save_every: 1000
  validate_every: 100    # 减少验证频率
  log_every: 10          # 增加日志频率
  max_checkpoints: 3

# 评估配置 - 简化评估
evaluation:
  enabled: false         # 暂时禁用评估减少复杂性
  
  metrics:
    - pseudo_perplexity
    - information_entropy
  
  generation:
    num_samples: 100     # 减少样本数
    guidance_scale: 2.0
    temperature: 1.0
    use_length_control: true
    
  evaluate_every: 10

# 输出配置
output:
  base_dir: "./outputs/separated_optimized_v1"
  checkpoint_dir: "./outputs/separated_optimized_v1/checkpoints"
  log_dir: "./outputs/separated_optimized_v1/logs"
  results_dir: "./outputs/separated_optimized_v1/results"
  
  save_model_config: true
  save_training_stats: true
  save_generated_samples: true

# 监控配置
monitoring:
  wandb:
    enabled: false
  tensorboard:
    enabled: false

# 调试和开发配置
debug:
  enabled: false
  detailed_logging: true

# 资源配置
resources:
  device: "cuda:2"
  available_gpus: [2, 3, 4, 5]
  stage1_gpus: [2, 3]
  stage2_gpus: [4, 5]
  gpu_memory_fraction: 0.8  # 减少GPU内存使用
  allow_growth: true
  num_threads: 4            # 减少CPU线程数
