# Test configuration for StructDiff training with ESMFold
experiment:
  name: "structdiff_test_esmfold"
  output_dir: "outputs"
  seed: 42

# Model configuration
model:
  # Sequence encoder settings
  sequence_encoder:
    pretrained_model: "facebook/esm2_t6_8M_UR50D"
    freeze_encoder: false
    hidden_dim: 320
    
  # Structure encoder settings
  structure_encoder:
    type: "MultiScaleStructureEncoder"
    use_esmfold: true
    hidden_dim: 320
    
  # Denoiser settings
  denoiser:
    num_layers: 4  # 减少层数
    num_heads: 8
    hidden_dim: 320
    dropout: 0.1
    use_cross_attention: true
    
  # Loss weights
  loss_weights:
    diffusion_loss: 1.0
    structure_consistency_loss: 0.1

# Diffusion settings (顶层配置)
diffusion:
  num_timesteps: 50  # 减少时间步数
  noise_schedule: "linear"  # 添加noise_schedule配置
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: "linear"

# Data configuration
data:
  train_path: "data/processed/train.csv"
  val_path: "data/processed/val.csv"
  batch_size: 1  # 小批量大小
  num_workers: 0
  pin_memory: false
  max_length: 50
  min_length: 8
  use_predicted_structures: true
  
  # Data augmentation
  augmentation:
    enable: false  # 暂时禁用增强
    mask_prob: 0.15

# Training configuration
training:
  num_epochs: 3
  gradient_accumulation_steps: 4
  gradient_clip: 1.0
  use_amp: false  # 禁用混合精度
  use_ema: false  # 禁用EMA
  ema_decay: 0.9999
  validate_every: 1
  max_checkpoints: 3
  
  # Optimizer settings
  optimizer:
    name: "adamw"
    lr: 1e-4
    weight_decay: 1e-6
    betas: [0.9, 0.999]
    
  # Scheduler settings
  scheduler:
    min_lr: 1e-6

# Logging configuration
logging:
  log_level: "INFO"
  log_every: 10

# Weights & Biases configuration
wandb:
  enabled: false
  project: "structdiff-test"
  tags: ["test", "esmfold"] 